### ISSUE TITLE
读取文件列表失败！TypeError: Failed to fetch

### ISSUE THREAD

**Issue by lcvy** [kaaass/sharepoint-list-plugin#1]
使用公开不登录的onedrive链接进行批量下载，会提示“读取文件列表失败！TypeError: Failed to fetch”，同时aria2批量下载得到的是100k的authorize

**Comment by kaaass** [comment]
你好，麻烦附上报错时控制台（Chrome浏览器Ctrl+Shift+I）的输出以便诊断。
如果方便的话，最好能提供一个可复现的分享链接，谢谢。

**Comment by lcvy** [comment]
请注意查收，若有乱码等现象，请及时回信取得联系，谢谢~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kaaass/sharepoint-list-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 晚上6:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kaaass/sharepoint-list-plugin] 读取文件列表失败！TypeError: Failed to fetch (#1)





 
你好，麻烦附上报错时控制台（Chrome浏览器Ctrl+Shift+I）的输出以便诊断。
 如果方便的话，最好能提供一个可复现的分享链接，谢谢。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kaaass** [comment]
我没看到附件相关的内容，猜测你可能是直接通过邮件回信了？如果是的话，请在 Issue 页面上传附件或者发送至邮箱 admin [AT] kaaass.net，不然我这看不到……

**Comment by lcvy** [comment]
已重发，请注意查收，谢谢~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kaaass/sharepoint-list-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月26日(星期天) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kaaass/sharepoint-list-plugin] 读取文件列表失败！TypeError: Failed to fetch (#1)





 
我没看到附件相关的内容，猜测你可能是直接通过邮件回信了？如果是的话，请在 Issue 页面上传附件或者发送至邮箱 admin [AT] kaaass.net，不然我这看不到……
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kaaass** [comment]
收到了，感谢反馈！

研究了一下，虽然链接我还是打不开（提示要登录），但是根据日志看了下，脚本应该是成功请求到了文件列表。但是错误日志里似乎没有记录到提示“读取文件列表失败！TypeError: Failed to fetch”对应的报错。请问是否是这样的情况：打开网页时报错，但是点击侧边栏可以正常加载文件列表。

关于 Aria2 下载，根据日志我推测你可能没有使用 [Tampermonkey Beta](https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf?hl=zh-CN) 版本，只有这个版本才可以支持 Aria2 下载。如果已经使用 Beta 版的话，请回复下具体的插件版本，我再研究下具体是啥原因。

**Comment by lcvy** [comment]
Tampermonkey Beta&nbsp;版本号为：v4.14.6143
有以下情况：
1、有文件列表
2、下载链接不能用idm或者aria2进行下载，前者403后者返回个空文件
3、多文件情况下会卡页面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kaaass/sharepoint-list-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月27日(星期一) 中午1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kaaass/sharepoint-list-plugin] 读取文件列表失败！TypeError: Failed to fetch (#1)





 
收到了，感谢反馈！
 
研究了一下，虽然链接我还是打不开（提示要登录），但是根据日志看了下，脚本应该是成功请求到了文件列表。但是错误日志里似乎没有记录到提示“读取文件列表失败！TypeError: Failed to fetch”对应的报错。请问是否是这样的情况：打开网页时报错，但是点击侧边栏可以正常加载文件列表。
 
关于 Aria2 下载，根据日志我推测你可能没有使用 &nbsp;版本，只有这个版本才可以支持 Aria2 下载。如果已经使用 Beta 版的话，请回复下具体的插件版本，我再研究下具体是啥原因。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1oveClub** [comment]
推送到aria2，结果却是authorize文件的原因已经定位了，是**因为脚本生成的cookie不完整**。

具体的详情我已经写在了论坛帖子里，作者可以把cookie读取功能更新一下

帖子链接：[https://bbs.1ove.club/thread-5777.htm](https://bbs.1ove.club/thread-5777.htm)

**Comment by kaaass** [comment]
@1oveClub 感谢提醒，修复版本将在测试后推送（预计今天日间）。

**Comment by kaaass** [comment]
本 BUG 已在 1.2.2 推送中修复，故关闭本 Issue。若还有问题请回复以再次打开。
