### ISSUE TITLE
下载的IDM导出文件（download.ef2）导入时无法被IDM识别

### ISSUE THREAD

**Issue by homurax** [kaaass/sharepoint-list-plugin#17]
提示：该文件不是有效的IDM导出文件，或文件已损坏

![0](https://github.com/kaaass/sharepoint-list-plugin/assets/42425496/5f6e8501-2199-49d6-a9ba-05eb94325cf1)

download.ef2：https://mega.nz/file/990nBAQI#WNi22VssJySvWv6Evatd8c3myvURHIeqTUfSCJ1miG8

IDM版本：6.42

**Comment by kaaass** [comment]
感谢报告，这个 `download.ef2` 是个空文件，暂时不确定是出了什么问题。在导出 ef2 之后浏览器控制台有出现什么错误提示吗？

**Comment by homurax** [comment]
> 感谢报告，这个 `download.ef2` 是个空文件，暂时不确定是出了什么问题。在导出 ef2 之后浏览器控制台有出现什么错误提示吗？

刚才又测试了一下，下载的 download.ef2 是包含内容可以正常导入 IDM 中使用的。

回忆了下当时的操作：
最初没有使用 Tampermonkey Beta，为了导出下载文件，后来在 Tampermonkey Beta 中安装了插件。即 Tampermonkey 和 Tampermonkey Beta 中插件都是启用状态。
当时页面上，四个功能按键（IDM下载、Aria下载、复制连接、批量下载）的 CSS 应该是有问题的，没有按钮样式，而是文字形式，但是当时我没有意识到。
现在依然是 Tampermonkey 和 Tampermonkey Beta 中插件都是启用状态。不过样式和获取的 download.ef2 都是正常的了。

目前无法复现这个问题。btw，两边都启用插件这样是否有问题？

**Comment by kaaass** [comment]
不建议这么做。理论上来说单个插件本身的功能应该没啥影响，但是根据加载顺序的不同实际生效的插件不一定是 BETA 版本的。

**Comment by homurax** [comment]
> 不建议这么做。理论上来说单个插件本身的功能应该没啥影响，但是根据加载顺序的不同实际生效的插件不一定是 BETA 版本的。

明白了，感谢。
