### ISSUE TITLE
脚本页面点击“Aria下载”无反应

### ISSUE THREAD

**Issue by ilhsyysyk** [kaaass/sharepoint-list-plugin#9]
我是这样配置的(配置如下)，然后就是复制链接到Aria2NG上可以正常下载
但是在脚本页面无法直接推送到Aria下载，点击无反应，请问怎么解决

[![bTZ6FH.png](https://s1.ax1x.com/2022/03/12/bTZ6FH.png)](https://imgtu.com/i/bTZ6FH)
[![bTZgfA.png](https://s1.ax1x.com/2022/03/12/bTZgfA.png)](https://imgtu.com/i/bTZgfA)
[![bTZcYd.png](https://s1.ax1x.com/2022/03/12/bTZcYd.png)](https://imgtu.com/i/bTZcYd)

**Comment by kaaass** [comment]
请检查是否已经在“设置-XHR 安全-用户域名白名单”添加 RPC 域名。参考：https://v2ex.com/t/802508

**Comment by ilhsyysyk** [comment]
“XHR 安全”没有这个选项，但是我在“设置-安全-白名单页面”里面添加了域名（ip），但是油猴无法保存这个设置，也无法生效

**Comment by ilhsyysyk** [comment]
> 请是否已经在“设置-XHR 安全-用户域名白名单”中添加RPC域名。参考：[https ://v2ex.com/t/802508](https://v2ex.com/t/802508)

“XHR 安全”没有这个选项，但是我在“设置-安全-白名单”里面添加了域名（ip），油猴无法设置这个设置，也无法生效

**Comment by kaaass** [comment]
几个问题：
1. 图片中填写的 URL 格式不正确。应该是：`ws://ip地址:6800/jsonrpc`
2. 在油猴插件 Beta 版（v4.15.6154）中，这个设置的位置是：编辑脚本-设置-XHR 安全-用户域名白名单。请再次检查版本、设置是否对应。

**Comment by ilhsyysyk** [comment]
> 几个问题：
> 
> 1. 图片中刷新的URL格式不正确，并且当前脚本不能使用WebSocket协议RPC。应该是：`http://ip地址:6800/jsonrpc`
> 2. 在油猴插件Beta版（v4.15.6154）中，这个设置的位置是：编辑脚本-设置-XHR 安全-用户域名白。再次检查版本、设置是否。

原来是在脚本设置里，我还以为在插件管理的设置中，现在已经成功了，多谢dalao

**Comment by kaaass** [comment]
没事～
